packages:
  teleinfo: !include
    file: packages_linky_modbus/teleinfo_map.yaml
    vars:
      teleinfo_id: linky
      rx_pin: 16
      alarm_pin: 17
      update_interval: 1s

  modbus1: !include
    file: packages_linky_modbus/modbus_map.yaml
    vars:
      bus_id: 1
      bus_address: 100
      baud_rate: 9600
      tx_pin: 13
      rx_pin: 21
      flow_control_pin: 14
      stop_bits: 1
      parity: NONE
      teleinfo_id: linky
      send_wait_time: 200ms


  modbus2: !include
    file: packages_linky_modbus/modbus_map.yaml
    vars:
      bus_id: 2
      bus_address: 100
      baud_rate: 9600
      tx_pin: 38
      rx_pin: 40
      flow_control_pin: 39
      stop_bits: 1
      parity: NONE
      teleinfo_id: linky
      send_wait_time: 200ms
